config/routes.rb
Rails.application.routes.draw do
  # root path
  root to: 'books#index'

  # authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  scope '/admin' do
    
    resources :users, except: [:show]
  	
  	resources :books
  	put 'books/:id/toogle_like', to: 'books#toogle_like'
  	
  	get 'manage_books', to: 'books#manage_books', as: 'manage_books'
  end
end

app/models/user.rb
class User < ApplicationRecord
  audited
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum kind: %i[librarian reader]

  after_initialize :set_default_kind

  validates :name, :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  has_many :user_books, dependent: :destroy
  has_many :books, through: :user_books


  def liked?(book)
    user_books.where(book: book).any?
  end

  private

  def set_default_kind
    if self.new_record?
      self.kind ||= :reader
    end
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_librarian_access
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'Usuário cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update_without_password(user_params)
        format.html { redirect_to users_url, notice: 'Usuário atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuário deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :kind, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <span class="alert-inner--text">Verifique os seguintes campos:</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <label for="userName">Nome</label>
        <%= form.text_field :name, class: 'form-control', id: 'userName', required: true %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label for="userEmail">Email</label>
        <%= form.email_field :email, class: 'form-control', id: 'userEmail', required: true %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <label for="cbbKind">Tipo</label>
        <%= form.select(:kind, User.kinds.keys.map {|at| [User.human_enum_name(:kind, at), at]}, {}, { class: 'custom-select' }) %>
      </div>
    </div>
    <% unless user.persisted? %>
    <div class="col-md-6">
      <div class="form-group">
        <label for="userPassword">Senha</label>
        <%= form.password_field :password, class: 'form-control', id: 'userPassword', autocomplete: "new-password", required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label for="userPasswordConfirmation">Confirmar senha</label>
        <%= form.password_field :password_confirmation, class: 'form-control', id: 'userPasswordConfirmation', autocomplete: "new-password", required: true %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= form.submit 'Salvar', class: 'btn btn-outline-success' %>
      <%= link_to 'Voltar', users_path, class: 'btn btn-outline-default' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Editar usuário</h3>
      </div>
      <div class="card-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Usuários</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
            <thead class="thead-light">
              <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Tipo</th>
                <th scope="col">#</th>
              </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= User.human_enum_name(:kind, user.kind) %></td>
                  <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <%= link_to edit_user_path(user), class: 'btn btn-icon btn-2 btn-outline-warning btn-sm', title: 'Editar' do %>
                        <span class="btn-inner--icon"><i class="fa fa-edit"></i></span>
                      <% end %>
                      <%= link_to user_path(user), class: 'btn btn-icon btn-2 btn-outline-danger btn-sm', title: 'Excluir', data: {confirm: 'Tem certeza?'}, method: :delete do %>
                        <span class="btn-inner--icon"><i class="fa fa-times"></i></span>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer py-4 text-right">
        <%= link_to 'Cadastrar', new_user_path, class: 'btn btn-outline-success' %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Cadastrar usuário</h3>
      </div>
      <div class="card-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>