config/routes.rb
Rails.application.routes.draw do
  # root path
  root to: 'books#index'

  # authentication
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  scope '/admin' do
    
    resources :users, except: [:show]
  	
  	resources :books
  	put 'books/:id/toogle_like', to: 'books#toogle_like'
  	
  	get 'manage_books', to: 'books#manage_books', as: 'manage_books'
  end
end

app/models/book.rb
class Book < ApplicationRecord
  audited
  
  validates :title, :description, :author, presence: true
  validates :image_url, allow_blank: false, 
    format: { with: %r{.(gif|jpg|png)\Z}i, message: 'URL informada não possui uma imagem válida' }

  has_many :user_books, dependent: :destroy
  has_many :users, through: :user_books

  scope :title_like, ->(query) { where("title LIKE ?", "%#{query}%") }
  scope :description_like, ->(query) { where("description LIKE ?", "%#{query}%") }
  scope :author_like, ->(query) { where("author LIKE ?", "%#{query}%") }
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_librarian_access, except: [:index, :toogle_like]
  before_action :set_book, only: [:show, :edit, :toogle_like, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    @books = @books.title_like(params[:title]) if params[:title].present?
    @books = @books.description_like(params[:description]) if params[:description].present?
    @books = @books.author_like(params[:author]) if params[:author].present?

    if params[:order].present? && params[:order] == "desc"
      @books = @books.order("title desc")
    else
      @books = @books.order("title asc")
    end
  end

  def manage_books
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # PUT
  def toogle_like
    if current_user.liked?(@book)
      UserBook.where(user: current_user, book: @book).destroy_all
      render json: {liked: false}
    else
      UserBook.create(user: current_user, book: @book)
      render json: {liked: true}
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to manage_books_path, notice: 'Livro cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to manage_books_path, notice: 'Livro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to manage_books_path, notice: 'Livro removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :image_url)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_list.html.erb
<% books.each do |book| %>
  <div class="col-md-4 col-sm-12">
    <div class="card mb-4">
      <img class="card-img-top" src="<%= book.image_url %>" alt="Card image cap" style="object-fit: none; width: 100%; height: 200px">
      <div class="card-body" style="height: 200px; overflow-y: scroll;">
        <h5 class="card-title"><%= book.title.truncate(30) %></h5>
        <p class="card-text" style="font-size: 13px"><%= ActionView::Base.full_sanitizer.sanitize(book.description)%></p>
      </div>
      <div class="card-footer">
        <div class="icons">
          <% if current_user.liked?(book) %>
            <i class="fas fa-star toogle" style="cursor: pointer;" data-id="<%= book.id %>" onclick="toogle_book(this)"></i>
          <% else %>
            <i class="far fa-star toogle" style="cursor: pointer;" data-id="<%= book.id %>" onclick="toogle_book(this)"></i>
          <% end %>
        </div>
        <span style="font-size: 12px" class="float-right"> <b>autor:</b> <%= book.author.truncate(30) %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <span class="alert-inner--text">Verifique os seguintes campos:</span>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label>Título</label>
        <%= form.text_field :title, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="form-group">
        <label>Descrição</label>
        <%= form.text_area :description, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Autor</label>
        <%= form.text_field :author, class: 'form-control', required: true %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <label>Imagem (URL)</label>
        <%= form.text_field :image_url, class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-right">
      <%= form.submit 'Salvar', class: 'btn btn-outline-success' %>
      <%= link_to 'Voltar', manage_books_path, class: 'btn btn-outline-default' %>
    </div>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Editar Livro</h3>
      </div>
      <div class="card-body">
        <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<style type="text/css">
.card-footer {
  position: relative;
}
.icons {
  position: absolute;
  font-size: 22px;
  top: 10px;
}
</style>

<div class="row mt-4">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Filtros
      </div>
      <div class="card-body collapse show" id="searchCollapse">
          <div class="row">
            <div class="col-md-3 form-group">
              <label class="form-control-label">Título</label>
              <input type="text" id="title" name="title" class="form-control" placeholder="título do livro" onkeyup="filter_books()">
            </div>
            <div class="col-md-3 form-group">
              <label class="form-control-label">Descrição</label>
              <input type="text" id="description" name="description" class="form-control" placeholder="descrição do livro" onkeyup="filter_books()">
            </div>
            <div class="col-md-3 form-group">
              <label class="form-control-label">Author</label>
              <input type="text" id="author" name="author" class="form-control" placeholder="autor do livro" onkeyup="filter_books()">
            </div>  
            <div class="col-md-3 form-group">
              <div class="form-group">
                <label for="cbbKind">Ordenação</label>
                <select class="custom-select" id="order" name="order" onchange="filter_books()">
                  <option value="asc">Título A-Z</option>
                  <option value="desc">Título Z-A</option>
                </select>
              </div>
            </div>  
          </div>
      </div>
    </div>
  </div>
</div>

<div class="row mt-4" id="books">
  <%= render 'book_list', books: @books %>
</div>

<script type="text/javascript">
  {
    function toogle_book(element){
      element = $(element);

      $.ajax({
        method: 'PUT',
        beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
        url: "/admin/books/"+ element.data("id") +"/toogle_like"
      }).done(function (resp) {
        if (resp.liked == true){
          $(element).removeClass('far').addClass('fas');
        }else{
          $(element).removeClass('fas').addClass('far');
        }
      });
    }

    function filter_books(){
      let title = $('#title').val();
      let description = $('#description').val();
      let author = $('#author').val();
      let order = $("#order").val();

      $.get( "/admin/books.js", { title: title, description: description, author: author, order: order });
    }
  }
</script>

app/views/books/index.js.erb
$('#books').html("<%= j render 'book_list', books: @books %>");

app/views/books/manage_books.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Livros Cadastrados</h3>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table id="datatable" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
            <thead class="thead-light">
              <tr>
                <th scope="col">Título</th>
                <th scope="col">Descrição</th>
                <th scope="col">Autor</th>
                <th scope="col">Foto</th>
                <th scope="col">#</th>

              </tr>
            </thead>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td><%= book.title.truncate(30) %></td>
                  <td><%= book.description.truncate(100) %></td>
                  <td><%= book.author %></td>
                  <td><%= image_tag(book.image_url, height: '100px') %></td>
                  <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <%= link_to edit_book_path(book), class: 'btn btn-icon btn-2 btn-outline-warning btn-sm', title: 'Editar' do %>
                        <span class="btn-inner--icon"><i class="fa fa-edit"></i></span>
                      <% end %>
                      <%= link_to book_path(book), class: 'btn btn-icon btn-2 btn-outline-danger btn-sm', title: 'Excluir', data: {confirm: 'Tem certeza?'}, method: :delete do %>
                        <span class="btn-inner--icon"><i class="fa fa-times"></i></span>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card-footer py-4 text-right">
        <%= link_to 'Cadastrar', new_book_path, class: 'btn btn-outline-success' %>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="row">
  <div class="col">
    <div class="card shadow mt-4">
      <div class="card-header border-0">
        <h3 class="mb-0">Cadastrar Livro</h3>
      </div>
      <div class="card-body">
        <%= render 'form', book: @book %>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @book.image_url %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>